version: "2"
services:
  frontend:
    build: ./frontend
    expose:
      - 80
    ports:
      - "4200:80"
    container_name: front-container
    restart: always
  backend:
    build: ./
    expose:
      - 8000
    ports:
      - "8000:8000"
    container_name: back-container
    restart: always
    links:
      - database
  database:
    build: ./server/database
    container_name: database
    expose:
      - 3306
    ports:
      - "3306:3306"
    restart: always
